[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = '''
  let g:rustfmt_autosave = 1

  if executable('rls')
    au User lsp_setup call lsp#register_server({
      \ 'name': 'rls',
      \ 'cmd': {server_info->['rustup', 'run', 'nightly', 'rls']},
      \ 'whitelist': ['rust'],
      \ })
  endif
'''

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'racer-rust/vim-racer'
