[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_post_source = '''
let g:deoplete#auto_complete_delay = 0
call deoplete#custom#option('sources', {
  \ '_': ['ale'],
  \ })

call deoplete#enable()
'''

[[plugins]]
repo = 'vim-scripts/L9'

[[plugins]]
repo = 'vim-scripts/FuzzyFinder'
hook_add = '''
let g:fuf_keyOpen = '<Tab>'
let g:fuf_keyOpenTabpage = '<CR>'
map <Leader>f :FufFile **/<CR>
map <Leader>b :FufBuffer<CR>
map <Leader>q :FufQuickfix<CR>
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
'''
hook_post_source = '''
AirlineTheme base16_default
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'w0rp/ale'
hook_post_source = '''
let g:ale_update_tagstack = 1
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1

let g:ale_c_parse_compile_commands = 1
let g:ale_c_parse_makefile = 1
let g:ale_c_clang_options = '-L. -I. -std=c11 -Wall'
let g:ale_c_clangd_options = '-background-index'

let g:ale_rust_rls_toolchain = 'nightly'

let g:ale_linters = {
  \ 'c':    ['clangd'],
  \ 'cpp':  ['clangd'],
  \ 'go':   ['gofmt', 'golint', 'go vet'],
  \ 'rust': ['rls', 'cargo'],
  \ }

let g:ale_fix_on_save = 1
let g:ale_fixers = {
  \ '*':    ['remove_trailing_lines', 'trim_whitespace'],
  \ 'c':    ['clang-format'],
  \ 'cpp':  ['clang-format'],
  \ 'go':   ['gofmt', 'goimports'],
  \ 'rust': ['rustfmt'],
  \ }

nnoremap <silent> gd :ALEGoToDefinitionInTab<CR>
'''

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'chriskempson/base16-vim'
on_event = ['VimEnter']
hook_post_source = '''
colorscheme base16-default-dark
'''
