[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-scripts/L9'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source $XDG_CONFIG_HOME/nvim/denite.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
'''
hook_post_source = '''
AirlineTheme base16_default
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = 0
hook_add = 'source $XDG_CONFIG_HOME/nvim/coc.vim'

[[plugins]]
repo = 'chriskempson/base16-vim'
merged = 0
hook_add = 'au VimEnter * nested colorscheme base16-default-dark'
