[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-syntastic/syntastic'
hook_post_source = '''
  set statusline+=%#warningmsg#
  set statusline+=%{SyntasticStatuslineFlag()}
  set statusline+=%*

  let g:syntastic_always_populate_loc_list = 1
  let g:syntastic_auto_loc_list = 1
  let g:syntastic_check_on_open = 1
  let g:syntastic_check_on_wq = 0
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]] # Theme
repo = 'ayu-theme/ayu-vim'
# on_event = ['VimEnter']
# hook_post_source = '''
#   let ayucolor='dark'
#   colorscheme ayu
#   highlight Visual ctermbg=11 guifg=#0F1419 guibg=#FFEE99
#   highlight LineNr ctermfg=4 guifg=#5C6773
# '''

[[plugins]]
repo = 'chriskempson/base16-vim'
on_event = ['VimEnter']
hook_post_source = '''
  colorscheme base16-default-dark
'''
