[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]] # Theme
repo = 'ayu-theme/ayu-vim'
on_event = ['VimEnter']
hook_post_source = '''
  let ayucolor='dark'
  colorscheme ayu
  highlight Visual ctermbg=11 guifg=#0F1419 guibg=#FFEE99
'''
